domains:
  - domain: '{{ app }}.{{ branch }}.{{ environment }}.local.parallax.dev'
    environments: '*'
    branches: '*'
  - domain: '{{ app }}.{{ environment }}.local.parallax.dev'
    environments: '*'
    branches: 'master'
afterDeploy:
  delete:
    - kind: Deployment
      namePattern: '{{ app }}-{{ branch }}-cron-*'
      nameApartFrom: '{{ app }}-{{ branch }}-cron-{{ build }}'
      namespace: '{{ namespace }}'