domains:
  - domain: '{{ app }}.{{ branch }}.{{ environment }}.local.parallax.dev'
    environments: '*'
    branches: '*'
  - domain: '{{ app }}.{{ environment }}.local.parallax.dev'
    environments: '*'
    branches: 'master'
afterDeploy:
  delete:
    - kind: Deployment
      namePattern: 'cron-{{ app }}-{{ branch }}-*'
      nameApartFrom: 'cron-{{ app }}-{{ branch }}-{{ build }}'
      namespace: '{{ namespace }}'
    - kind: Deployment
      namePattern: '{{ app }}-{{ branch }}-*'
      nameApartFrom: '{{ app }}-{{ branch }}-{{ build }}'
      namespace: '{{ namespace }}'