apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: 'uptime.local.parallax.dev'
  namespace: 'uptime'
spec:
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - 'uptime.local.parallax.dev'
  commonName: 'uptime.local.parallax.dev'
  dnsNames:
  - 'uptime.local.parallax.dev'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: 'uptime-ssl'