apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
  labels:
    app: '{{ app }}-{{ branch }}-cron-{{ build }}'
  name: '{{ app }}-{{ branch }}-cron-{{ build }}'
  namespace: '{{ namespace }}'
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: '{{ app }}-{{ branch }}-cron-{{ build }}'
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        app: '{{ app }}-{{ branch }}-cron-{{ build }}'
    spec:
      volumes:
        - name: shared-files
          emptyDir: {}
      containers:
      - name: php
        image: '{{ image_php_fpm }}'
        command: ["/start-cron.sh"]
        env:
        - name: ENVIRONMENT
          value: 'production'
        - name: SITE_NAME
          value: 'uptime'
        - name: SITE_BRANCH
          value: 'master'
        - name: BUILD
          value: '1'
        - name: APP_ENV
          value: 'production'
        - name: LOG_CHANNEL
          value: 'stderr'
        - name: APP_URL
          value: 'uptime.local.parallax.dev'
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 64Mi
        volumeMounts:
          - name: shared-files
            mountPath: /src-shared
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 20